---
- name: Apariencia - Wallpaper
  tags: appearence_wallpaper
  become: true
  become_user: "{{ diego_remote_regular_user }}"
  block:
    - name: Apariencia - Asegurar que ~/Pictures existe
      ansible.builtin.file:
        path: "{{ diego_remote_home }}/Pictures"
        state: directory
        mode: "0755"

    - name: Apariencia - Copiar wallpaper y lockscreen
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
      with_items:
        - { src: ./files/wallpaper01.jpg, dest: "{{ diego_remote_home }}/Pictures/wallpaper01.jpg" }
        - { src: ./files/wallpaper02.jpg, dest: "{{ diego_remote_home }}/Pictures/wallpaper02.jpg" }
        - { src: ./files/profile_picture.jpg, dest: "{{ diego_remote_home }}/Pictures/profile_picture.jpg" }

    - name: Apariencia - Set Wallpaper
      community.general.dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file://{{ diego_remote_home }}/Pictures/wallpaper01.jpg'"
        state: present

    - name: Apariencia - Set screensaver picture
      community.general.dconf:
        key: "/org/gnome/desktop/screensaver/picture-uri"
        value: "'file://{{ diego_remote_home }}/Pictures/wallpaper02.jpg'"
        state: present

    - name: Apariencia - Set back position
      community.general.dconf:
        key: "/org/gnome/desktop/background/picture-options"
        value: "'zoom'"
        state: present

- name: Apariencia - Gnome
  tags: appearence_gnome
  become: true
  become_user: "{{ diego_remote_regular_user }}"
  block:
    - name: Apariencia - Instalar numix icon pack
      become: true
      become_user: root
      ansible.builtin.apt:
        name: numix-icon-theme-circle
        state: present

    - name: Apariencia - Personalizaciones de gnome
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - { key: "/org/gnome/desktop/interface/clock-show-seconds", value: "false" }
        - { key: "/org/gnome/desktop/interface/enable-animations", value: "false" }
        - { key: "/org/gnome/desktop/interface/icon-theme", value: "'Numix-Circle'" }
        - { key: "/org/gnome/mutter/workspaces-only-on-primary", value: "true" }
