---
- name: Apariencia - Wallpaper
  tags: appearence_wallpaper
  block:
    - name: Apariencia - Copiar wallpaper y lockscreenfile
      become_user: "{{ lookup('env','USER') }}"
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - {
            src: ./files/wallpaper01.jpg,
            dest: "/home/{{ lookup('env','USER') }}/Pictures/wallpaper01.jpg",
          }
        - {
            src: ./files/wallpaper02.jpg,
            dest: "/home/{{ lookup('env','USER') }}/Pictures/wallpaper02.jpg",
          }
        - {
            src: ./files/profile_picture.jpg,
            dest: "/home/{{ lookup('env','USER') }}/Pictures/profile_picture.jpg",
          }

    - name: Apariencia - Set Wallpaper
      become_user: "{{ lookup('env','USER') }}"
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///home/{{ lookup('env','USER') }}/Pictures/wallpaper01.jpg'"
        state: present

    - name: Apariencia - Set screensaver picture
      become_user: "{{ lookup('env','USER') }}"
      dconf:
        key: "/org/gnome/desktop/screensaver/picture-uri"
        value: "'file:///home/{{ lookup('env','USER') }}/Pictures/wallpaper02.jpg'"
        state: present

    - name: Apariencia - Set back position
      become_user: "{{ lookup('env','USER') }}"
      dconf:
        key: "/org/gnome/desktop/background/picture-options"
        value: "'zoom'"
        state: present

- name: Apariencia - Gnome
  tags: appearence_gnome
  block:
    - name: Apariencia - Instalar numix icon pack
      apt:
        name:
          - numix-icon-theme-circle
        state: present

    - name: Apariencia - Personalizaciones de gnome
      become_user: "{{ lookup('env','USER') }}"
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - {
            key: "/org/gnome/desktop/interface/icon-theme",
            value: "'Numix-Circle'",
          }
        # Determina si el cambio entre áreas de trabajo debería suceder para las ventanas en todos los monitores o sólo para ventanas en el monitor primario.
        - {
            key: "/org/gnome/mutter/workspaces-only-on-primary",
            value: "'true'",
          }

