---
- name: Browsers - Instalar Google Chrome
  tags: chrome
  block:
    - name: Chrome - Descargar y volcar clave GPG (dearmor)
      ansible.builtin.get_url:
        url: https://dl.google.com/linux/linux_signing_key.pub
        dest: /tmp/google-chrome.asc
        mode: "0644"

    - name: Chrome - Dearmor clave GPG
      ansible.builtin.command: gpg --yes --dearmor --output /usr/share/keyrings/google-chrome-keyring.gpg /tmp/google-chrome.asc
      args:
        creates: /usr/share/keyrings/google-chrome-keyring.gpg

    - name: Chrome - Agregar repositorio
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main"
        filename: google-chrome

    - name: Chrome - Instalar
      ansible.builtin.apt:
        name: google-chrome-stable
        state: present
        update_cache: true

- name: Browsers - Instalar Firefox (ESR, repos de Debian)
  tags: firefox
  ansible.builtin.apt:
    name: firefox-esr
    state: present
