---
- name: Docker - Install and configure (with docker-compose)
  become: true
  block:
    - name: Docker - Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - lsb-release
        state: present

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg
      register: gpg_key_download

    - name: Ensure Docker GPG key is downloaded
      fail:
        msg: "Failed to download Docker GPG key"
      when: gpg_key_download.failed

    - name: Import Docker GPG key
      apt_key:
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg
        id: 0EBFCD88

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Docker - Add Docker repository
      apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable
        state: present
        filename: docker

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-compose-plugin
        update_cache: yes
        state: present

    - name: Docker - Execute commands as root
      block:
        - name: Docker - Create docker group
          group:
            name: docker
            state: present

        - name: Docker - Add users to the docker group
          user:
            name: "{{ ansible_env.SUDO_USER }}"
            groups: ["docker"]
            append: yes
