---
- name: Docker - Instalar y configurar (con docker compose)
  tags: docker
  block:
    - name: Docker - Instalar dependencias
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Docker - Descargar y volcar clave GPG (dearmor)
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /tmp/docker.asc
        mode: "0644"

    - name: Docker - Dearmor clave GPG
      ansible.builtin.command: gpg --yes --dearmor --output /usr/share/keyrings/docker-keyring.gpg /tmp/docker.asc
      args:
        creates: /usr/share/keyrings/docker-keyring.gpg

    - name: Docker - Agregar repositorio
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-keyring.gpg]
          https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        filename: docker

    - name: Docker - Instalar docker y docker compose plugin
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-compose-plugin
        update_cache: true
        state: present

    - name: Docker - Crear grupo docker
      ansible.builtin.group:
        name: docker
        state: present

    - name: Docker - Agregar usuario al grupo docker
      ansible.builtin.user:
        name: "{{ diego_remote_regular_user }}"
        groups: ["docker"]
        append: true
