---
- name: GitHub CLI
  block:
    - name: Agregar clave GPG y repositorio de GitHub CLI
      get_url:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
      environment:
        DEBIAN_FRONTEND: noninteractive
      become_method: sudo
      tags:
        - github_cli

    - name: Agregar repositorio de GitHub CLI
      apt_repository:
        filename: github-cli
        repo: "deb [arch=x86_64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
        state: present
      tags:
        - github_cli

    - name: Instalar GitHub CLI
      apt:
        name: gh
        state: present
      tags:
        - github_cli

- name: Git - Definiendo code por defecto y configuraciones globales
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - { name: user.email, value: diegobollini@protonmail.com }
    - { name: user.name, value: diegobollini }
    - { name: core.editor, value: code --wait }
    - { name: diff.tool, value: default-difftool }
    - {
        name: difftool.default-difftool.cmd,
        value: code --wait --diff \$LOCAL \$REMOTE,
      }
    - { name: push.default, value: nothing }
    - { name: pull.default, value: nothing }
    - { name: pull.ff, value: only }
  tags: git_config
