---
- name: GitHub CLI
  tags: [git, github_cli]
  block:
    - name: Agregar clave GPG y repositorio de GitHub CLI
      ansible.builtin.get_url:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
        mode: "0644"

    - name: Agregar repositorio de GitHub CLI
      ansible.builtin.apt_repository:
        filename: github-cli
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
        state: present

    - name: Instalar GitHub CLI
      ansible.builtin.apt:
        name: gh
        state: present

- name: Git - Definiendo code por defecto y configuraciones globales
  become: true
  become_user: "{{ diego_remote_regular_user }}"
  community.general.git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - { name: user.email, value: "{{ diego_git_user_email }}" }
    - { name: user.name, value: "{{ diego_git_user_name }}" }
    - { name: core.editor, value: code --wait }
    - { name: diff.tool, value: default-difftool }
    - { name: difftool.default-difftool.cmd, value: "code --wait --diff \\$LOCAL \\$REMOTE" }
    - { name: push.default, value: nothing }
    - { name: pull.default, value: nothing }
    - { name: pull.ff, value: only }
  tags: [git, git_config]
