---
- name: Idioma - Agregar y configurar es
  tags: language
  block:
    - name: Idioma - Instalar soporte de locales
      ansible.builtin.apt:
        name: locales
        state: present

    - name: Idioma - Generar locale
      community.general.locale_gen:
        name: "{{ diego_locale_target }}"
        state: present

    - name: Idioma - Configurar layout de teclado
      become: true
      become_user: "{{ diego_remote_regular_user }}"
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/sources"
        value: "[('xkb', '{{ diego_keyboard_layout }}')]"
        state: present
