---
- name: Idioma - Agregar y configurar es
  tags: language
  block:
    - name: Idioma - Validar que locale existe
      locale_gen:
        name: es_ES.UTF-8
        state: present

    - name: Idioma - Configurar layouts de teclado
      become_user: "{{ remote_regular_user }}"
      dconf:
        key: "/org/gnome/desktop/input-sources/sources"
        value: "[('xkb', 'es')]"
        state: present
