---
# vars/main.yml se carga automáticamente por convención de Ansible
- name: Aplicar rol diego
  block:
    - name: Importar packages.yml
      ansible.builtin.import_tasks: packages.yml
    - name: Importar browsers.yml
      ansible.builtin.import_tasks: browsers.yml
    - name: Importar language.yml
      ansible.builtin.import_tasks: language.yml
    - name: Importar social.yml
      ansible.builtin.import_tasks: social.yml
    - name: Importar appearence.yml
      ansible.builtin.import_tasks: appearence.yml
    - name: Importar ssh.yml
      ansible.builtin.import_tasks: ssh.yml
    - name: Importar code.yml
      ansible.builtin.import_tasks: code.yml
    - name: Importar python.yml
      ansible.builtin.import_tasks: python.yml
    - name: Importar docker.yml
      ansible.builtin.import_tasks: docker.yml
    - name: Importar git.yml
      ansible.builtin.import_tasks: git.yml
    - name: Importar meld.yml
      ansible.builtin.import_tasks: meld.yml
    - name: Importar zsh.yml
      ansible.builtin.import_tasks: zsh.yml
    - name: Importar security.yml
      ansible.builtin.import_tasks: security.yml
    - name: Importar network.yml
      ansible.builtin.import_tasks: network.yml
    - name: Importar tweaks.yml
      ansible.builtin.import_tasks: tweaks.yml
