---
- name: Set custom DNS servers in Network Manager
  tags: dns
  ansible.builtin.lineinfile:
    dest: /etc/NetworkManager/NetworkManager.conf
    regexp: "^dns=.*"
    line: "dns={{ diego_dns_servers }}"
    state: present
  notify: Restart NetworkManager
