---
- name: Set custom DNS servers in Network Manager
  tags: dns
  lineinfile:
    dest: /etc/NetworkManager/NetworkManager.conf
    regexp: "^dns=.*"
    line: "dns=8.8.8.8,1.1.1.1"
    state: present
