---
- name: SSH - Key y config
  tags: ssh
  block:
    - name: SSH - Crear directorios si no existen
      become: true
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ ansible_env.HOME }}/.ssh"
        - "{{ ansible_env.HOME }}/.ssh/config"

    - name: SSH - Copiar llave pública
      copy:
        src: ./files/private_key_diego.pub
        dest: /home/{{ lookup('env','USER') }}/.ssh/private_key_diego.pub
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','USER') }}"
        mode: 744

    - name: SSH - Copiar configuraciones de sshconfig
      copy:
        src: ./files/ssh_config
        dest: /home/{{ lookup('env','USER') }}/.ssh/config
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','USER') }}"
        mode: 744
