---
- name: SSH - Copiar llave pública
  copy:
    src: ./files/private_key_diego.pub
    dest: /home/{{ remote_regular_user }}/.ssh/private_key_diego.pub
    owner: "{{ remote_regular_user }}"
    group: "{{ remote_regular_user }}"
    mode: 744

- name: SSH - Copiar configuraciones de sshconfig
  copy:
    src: ./files/sshconfig
    dest: /home/{{ remote_regular_user }}/.ssh/config
    owner: "{{ remote_regular_user }}"
    group: "{{ remote_regular_user }}"
    mode: 744
