---
- name: Tweaks - Extensiones Gnome
  tags: extensions
  block:
    - name: Tweaks - Instalar gnome tweaks y dependencias
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - gnome-tweaks
          - gnome-shell-extension-manager
          - gnome-browser-connector
          - dbus-x11
          - gnome-shell-extensions

    # Install the Extensions using https://github.com/ToasterUwU/install-gnome-extensions
    - name: Tweaks - Descargar script para instalar gnome extensions
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ToasterUwU/install-gnome-extensions/master/install-gnome-extensions.sh
        dest: /tmp/install-gnome-extensions.sh
        mode: "0755"

    - name: Tweaks - Instalar gnome extensions con script
      become: true
      become_user: "{{ diego_remote_regular_user }}"
      ansible.builtin.script: "/tmp/install-gnome-extensions.sh --overwrite --enable {{ diego_gnome_extension_ids | join(' ') }}"
      changed_when: false
      # ids -> https://extensions.gnome.org/extension/<id>/ (ver vars/main.yml)

- name: Tweaks - Dock y favoritos
  tags: dock
  become: true
  become_user: "{{ diego_remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "[{{ diego_gnome_favorite_apps | map('regex_replace', '^(.*)$', \"'\\1'\") | join(', ') }}]"
    state: present
