---
# Para instalar zsh y omz. La idea es usar stow y dotfiles para el resto de la configuración, theme, plugins, etc.
- name: Zsh - Instalar y configurar
  tags: zsh
  block:
    - name: Zsh - Instalar
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - zsh
          - zsh-autosuggestions
          - zsh-syntax-highlighting
          - fonts-powerline

    - name: Zsh - Set as default shell
      ansible.builtin.user:
        name: "{{ diego_remote_regular_user }}"
        shell: /usr/bin/zsh

    - name: Zsh - Copiar archivo de configuración
      become: true
      become_user: "{{ diego_remote_regular_user }}"
      ansible.builtin.copy:
        src: ./files/.zshrc
        dest: "{{ diego_remote_home }}/.zshrc"
        mode: "0644"

# https://github.com/ohmyzsh/ohmyzsh
- name: Omz - Instalar, configurar y plugins
  tags: omz
  become: true
  become_user: "{{ diego_remote_regular_user }}"
  block:
    - name: Omz - Descargar script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/omz_install.sh
        mode: "0755"
        force: true

    - name: Omz - Instalar (si no está instalado)
      ansible.builtin.script: /tmp/omz_install.sh --unattended
      args:
        creates: "{{ diego_remote_home }}/.oh-my-zsh"

    # https://github.com/cantino/mcfly
    - name: Mcfly - Descargar script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/cantino/mcfly/master/ci/install.sh
        dest: /tmp/mcfly_install.sh
        mode: "0755"
        force: true

    - name: Mcfly - Asegurar ~/.local/bin
      ansible.builtin.file:
        path: "{{ diego_remote_home }}/.local/bin"
        state: directory
        mode: "0755"

    - name: Mcfly - Instalar (si no está instalado)
      ansible.builtin.script: /tmp/mcfly_install.sh --git cantino/mcfly --to {{ diego_remote_home }}/.local/bin
      args:
        creates: "{{ diego_remote_home }}/.local/bin/mcfly"

    - name: Omz - Clonar varios plugins
      ansible.builtin.git: # noqa: latest
        repo: "{{ item.key }}"
        dest: "{{ diego_remote_home }}/.oh-my-zsh/custom/plugins/{{ item.value }}"
        clone: true
        update: true
      with_items:
        - { key: "https://github.com/zsh-users/zsh-syntax-highlighting.git", value: zsh-syntax-highlighting }
        - { key: "https://github.com/zsh-users/zsh-autosuggestions", value: zsh-autosuggestions }
        - { key: "https://github.com/zsh-users/zsh-completions", value: zsh-completions }

    # https://github.com/romkatv/powerlevel10k
    - name: Zsh - Powerlevel10k theme
      ansible.builtin.git: # noqa: latest
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "{{ diego_remote_home }}/.oh-my-zsh/custom/themes/powerlevel10k"
        clone: true
        update: true
        depth: 1
